name: PR CI
on:
  pull_request:
    branches: ["master"]
  # In urgent cases we allow to manually trigger this step
  workflow_dispatch:
  workflow_call:
jobs:
  ci:
    uses: ./.github/workflows/java-config.yml
    name: Test & Build
    secrets: inherit
    with:
      java-version: ${{ vars.JAVA_VERSION }}