name: PR CI
on:
  pull_request:
    branches: ["master"]
  # In urgent cases we allow to manually trigger this step
  workflow_dispatch:
  workflow_call:
jobs:
  ci:
    steps:
      - name: Test & Build
        uses: ./.github/workflows/java-config.yml
        secrets: inherit
        with:
          java-version: ${{ vars.JAVA_VERSION }}